---
abstract: 'A resource and booking management tool for the greedy'
author:
  - 'Alex Muntada'
build_requires:
  Data::Compare: 0
  Data::Dumper::Simple: 0
  ExtUtils::MakeMaker: 6.36
  File::Copy: 0
  JSON: 0
  List::Compare: 0
  Path::Class: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Text::CSV: 0
  utf8::all: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: agpl_3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: V2-Server
no_index:
  directory:
    - doc
    - inc
    - t
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Controller::REST: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Plugin::Unicode: 0
  Catalyst::View::JSON: 0
  Catalyst::View::TT: 0
  DBD::SQLite: 0
  DBIx::Class: 0
  DBIx::Class::TimeStamp: 0
  Data::ICal: 0
  Date::ICal: 0
  DateTime: 0
  DateTime::Event::ICal: 0
  DateTime::Format::SQLite: 0
  DateTime::Span: 0
  Exception::Class::TryCatch: 0
  File::Path: 0
  Getopt::Euclid: 0
  HTTP::Server::Simple::CGI: 0
  HTTP::Status: 5.817
  Set::Object: 0
  XML::LibXML: 0
  XML::Simple: 0
version: 2.10
