---
abstract: ~
author:
  - 'Alex Muntada (ALEXM)'
build_requires:
  Data::Compare: 0
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: agpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: V2-Server
no_index:
  directory:
    - doc
    - dtd
    - inc
    - share
    - t
    - xt
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Controller::REST: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Plugin::Unicode: 0
  Catalyst::View::JSON: 0
  Catalyst::View::TT: 0
  DBIx::Class: 0
  DBIx::Class::TimeStamp: 0
  Data::ICal: 0
  Date::ICal: 0
  DateTime: 0
  DateTime::Event::ICal: 0
  DateTime::Format::SQLite: 0
  DateTime::Span: 0
  File::Path: 0
  Getopt::Euclid: 0
  HTTP::Server::Simple::CGI: 0
  HTTP::Status: 5.817
  Set::Object: 0
  XML::LibXML: 0
  XML::Simple: 0
version: 2.01
