[   {   title => 'CreaTag t1',
        uri   => '/tag',
        op    => 'POST',
        input => { id => 't1', description => 'tag 1' },
        status  => sub { shift->code == HTTP_CREATED },
        new_ids => 1,
        output  => [],
    },
    {   title => 'CreaTag t2',
        uri   => '/tag',
        op    => 'POST',
        input => { id => 't2', description => 'tag 2' },
        status  => sub { shift->code == HTTP_CREATED },
        new_ids => 1,
        output  => [],
    },
    {   title => 'Crea Recurs aula',
        uri   => '/resource',
        op    => 'POST',
        input => {
            description => 'aula',
            info        => 'resource info',
        },
        status  => sub { shift->code == HTTP_CREATED },
        new_ids => 1,
        output  => [],
    },
    {   title => 'Crea Event simposi',
        uri   => '/event',
        op    => 'POST',
        input => {
            description => 'simposi',
            info        => 'simposi info',
            starts      => '2012-04-01T08:00:00',
            ends        => '2012-04-10T14:00:00',
        },
        status  => sub { shift->code == HTTP_CREATED },
        new_ids => 1,
        output  => [],
    },
    {   title => 'Creo un booking',
        uri   => '/booking',
        op    => 'POST',
        input => {
            info        => 'info booking',
            id_resource => sub { get_generated_id('resource'); },
            id_event    => sub { get_generated_id('event'); },
            dtstart     => '2012-04-01T08:00:00',
            dtend       => '2012-04-01T10:00:00',
            frequency   => 'daily',
        },
        status  => sub { shift->code == HTTP_CREATED },
        new_ids => 1,
        output  => [],
    },
    {   title => 'Obte tags del booking quan no té encara cap tag',
        uri => [ '/booking/', sub { get_generated_id('booking'); }, '/tag' ],
        op  => 'GET',
        status => sub { shift->code == HTTP_MOVED_PERMANENTLY },
        output => [],
    },
    {   title =>
            'Obté tags del booking quan no té encara cap tag (sense redirect)',
        uri => [ '/tag/?booking=', sub { get_generated_id('booking'); } ],
        op  => 'GET',
        status => sub { shift->code == HTTP_OK },
        output => [],
    },
    {   title => 'Assigna el tag t1 al booking',
        uri => [ '/booking/', sub { get_generated_id('booking'); }, '/tag' ],
        id  => 't1',
        input  => {},
        op     => 'PUT',
        status => sub { shift->code == HTTP_OK },
        output => [],
    },
    {   title => 'Obte tags del booking quan només té el tag t1',
        uri   => [ 'tag?booking=', sub { get_generated_id('booking'); } ],
        op    => 'GET',
        status => sub { shift->code == HTTP_OK },
        output => [ { id => 't1', description => 'tag 1' } ],
    },
    {   title => 'Comprova que el booking NO té assignat el tag t2',
        uri   => [
            '/booking/', sub { get_generated_id('booking'); },
            '/tag/dummy'
        ],
        op     => 'GET',
        status => sub { shift->code == HTTP_NOT_FOUND },
        output => [],
    },
    {   title => 'Intenta assignar el tag t2 al booking (invalid method)',
        uri => [ '/booking/', sub { get_generated_id('booking'); }, '/tag' ],
        input  => {},
        op     => 'POST',
        status => sub { shift->code == HTTP_METHOD_NOT_ALLOWED },
        output => [],
    },
    {   title => 'Assigna el tag t2 al booking',
        uri => [ '/booking/', sub { get_generated_id('booking'); }, '/tag' ],
        id  => 't2',
        input  => {},
        op     => 'PUT',
        status => sub { shift->code == HTTP_OK },
        output => [],
    },
    {   title => 'Obte els tags del booking quan té assignats t1 i t2',
        uri   => [ 'tag?booking=', sub { get_generated_id('booking'); } ],
        op    => 'GET',
        status => sub { shift->code == HTTP_OK },
        output => [
            { id => 't1', description => 'tag 1' },
            { id => 't2', description => 'tag 2' }
        ],
    },
    {   title =>
            'Obté tags del booking quan té assignats t1 i t2 (sense redirect)',
        uri => [ '/tag/?booking=', sub { get_generated_id('booking'); } ],
        op  => 'GET',
        status => sub { shift->code == HTTP_OK },
        output => [
            { id => 't1', description => 'tag 1' },
            { id => 't2', description => 'tag 2' }
        ],
    },
    {   title  => 'Obté tags d\'un booking inexistent',
        uri    => '/tag/?booking=123345678',
        op     => 'GET',
        status => sub { shift->code == HTTP_NOT_FOUND },
        output => [],
    },
    {   title => 'Comprova que el booking té assignat el tag t2',
        uri =>
            [ '/booking/', sub { get_generated_id('booking'); }, '/tag/t2' ],
        op     => 'GET',
        status => sub { shift->code == HTTP_OK },
        output => [],
    },
    {   title => 'Comprova que el booking NO té assignat un tag inexistent',
        uri   => [
            '/booking/', sub { get_generated_id('booking'); },
            '/tag/dummy'
        ],
        op     => 'GET',
        status => sub { shift->code == HTTP_NOT_FOUND },
        output => [],
    },
    {   title => 'Intenta assignar al booking un tag inexistent',
        uri => [ '/booking/', sub { get_generated_id('booking'); }, '/tag' ],
        id  => 'dummy',
        input  => {},
        op     => 'PUT',
        status => sub { shift->code == HTTP_NOT_FOUND },
        output => [],
    },
    {   title => 'Intenta treure-li un tag no assignat al booking',
        uri => [ '/booking/', sub { get_generated_id('booking'); }, '/tag' ],
        id  => 'dummy',
        op  => 'DELETE',
        status => sub { shift->code == HTTP_NOT_FOUND },
        output => [],
    },
    {   title => 'Treu el tag t2 al booking',
        uri => [ '/booking/', sub { get_generated_id('booking'); }, '/tag' ],
        id  => 't2',
        op  => 'DELETE',
        status => sub { shift->code == HTTP_OK },
        output => [],
    },
    {   title => 'Treu el tag t2 al booking (que ara ja no el té assignat)',
        uri => [ '/booking/', sub { get_generated_id('booking'); }, '/tag' ],
        id  => 't2',
        op  => 'DELETE',
        status => sub { shift->code == HTTP_NOT_FOUND },
        output => [],
    },
]
