[   {   title => 'CreaTag t1',
        uri   => '/tag',
        op    => 'POST',
        input => { id => 't1', description => 'tag 1' },
        status  => sub { shift->code == HTTP_CREATED },
        new_ids => 1,
        output  => [],
    },
    {   title => 'CreaTag t2',
        uri   => '/tag',
        op    => 'POST',
        input => { id => 't2', description => 'tag 2' },
        status  => sub { shift->code == HTTP_CREATED },
        new_ids => 1,
        output  => [],
    },
    {   title => 'Crea Event simposi',
        uri   => '/event',
        op    => 'POST',
        input => {
            description => 'simposi',
            info        => 'info del simposi',
            starts      => '2012-04-01T08:00:00',
            ends        => '2012-04-10T14:00:00',
        },
        status  => sub { shift->code == HTTP_CREATED },
        new_ids => 1,
        output  => [],
    },
    {   title => 'Obte tags de l\'event simposi quan no té encara cap tag',
        uri   => [ '/event/', \&get_generated_id, '/tag' ],
        op    => 'GET',
        status => sub { shift->code == HTTP_MOVED_PERMANENTLY },
        output => [],
    },
    {   title =>
            'Obté tags de l\'event simposi quan no té encara cap tag (sense redirect)',
        uri    => [ '/tag/?event=', \&get_generated_id ],
        op     => 'GET',
        status => sub               { shift->code == HTTP_OK },
        output => [],
    },
    {   title => 'Assigna el tag t1 a l\'event simposi',
        uri   => [ '/event/', \&get_generated_id, '/tag' ],
        id    => 't1',
        input => {},
        op    => 'PUT',
        status => sub { shift->code == HTTP_OK },
        output => [],
    },
    {   title  => 'Obte tags de l\'event simposi quan només té el tag t1',
        uri    => [ 'tag?event=', \&get_generated_id ],
        op     => 'GET',
        status => sub { shift->code == HTTP_OK },
        output => [ { id => 't1', description => 'tag 1' } ],
    },
    {   title => 'Comprova que l\'event simposi NO té assignat el tag t2',
        uri   => [ '/event/', \&get_generated_id, '/tag/dummy' ],
        op    => 'GET',
        status => sub { shift->code == HTTP_NOT_FOUND },
        output => [],
    },
    {   title =>
            'Intenta assignar el tag t2 a l\'event simposi (invalid method)',
        uri   => [ '/event/', \&get_generated_id, '/tag' ],
        input => {},
        op    => 'POST',
        status => sub { shift->code == HTTP_METHOD_NOT_ALLOWED },
        output => [],
    },
    {   title => 'Assigna el tag t2 a l\'event simposi',
        uri   => [ '/event/', \&get_generated_id, '/tag' ],
        id    => 't2',
        input => {},
        op    => 'PUT',
        status => sub { shift->code == HTTP_OK },
        output => [],
    },
    {   title =>
            'Obte els tags de l\'event simposi quan té assignats t1 i t2',
        uri    => [ 'tag?event=', \&get_generated_id ],
        op     => 'GET',
        status => sub             { shift->code == HTTP_OK },
        output => [
            { id => 't1', description => 'tag 1' },
            { id => 't2', description => 'tag 2' }
        ],
    },
    {   title =>
            'Obté tags de l\'event simposi quan té assignats t1 i t2 (sense redirect)',
        uri    => [ '/tag/?event=', \&get_generated_id ],
        op     => 'GET',
        status => sub               { shift->code == HTTP_OK },
        output => [
            { id => 't1', description => 'tag 1' },
            { id => 't2', description => 'tag 2' }
        ],
    },
    {   title  => 'Obté tags d\'un event inexistent',
        uri    => '/tag/?event=123345678',
        op     => 'GET',
        status => sub { shift->code == HTTP_NOT_FOUND },
        output => [],
    },
    {   title => 'Comprova que l\'event simposi té assignat el tag t2',
        uri   => [ '/event/', \&get_generated_id, '/tag/t2' ],
        op    => 'GET',
        status => sub { shift->code == HTTP_OK },
        output => [],
    },
    {   title =>
            'Comprova que l\'event simposi NO té assignat un tag inexistent',
        uri => [ '/event/', \&get_generated_id, '/tag/dummy' ],
        op  => 'GET',
        status => sub { shift->code == HTTP_NOT_FOUND },
        output => [],
    },
    {   title => 'Intenta assignar a l\'event simposi un tag inexistent',
        uri   => [ '/event/', \&get_generated_id, '/tag' ],
        id    => 'dummy',
        input => {},
        op    => 'PUT',
        status => sub { shift->code == HTTP_NOT_FOUND },
        output => [],
    },
    {   title =>
            'Intenta treure-li a l\'event siposi un tag que no té assignat',
        uri => [ '/event/', \&get_generated_id, '/tag' ],
        id  => 'dummy',
        op  => 'DELETE',
        status => sub { shift->code == HTTP_NOT_FOUND },
        output => [],
    },
    {   title => 'Treu el tag t2 a l\'event simposi',
        uri   => [ '/event/', \&get_generated_id, '/tag' ],
        id    => 't2',
        op    => 'DELETE',
        status => sub { shift->code == HTTP_OK },
        output => [],
    },
    {   title =>
            'Treu el tag t2 a l\'event simposi (que ara ja no el té assignat)',
        uri => [ '/event/', \&get_generated_id, '/tag' ],
        id  => 't2',
        op  => 'DELETE',
        status => sub { shift->code == HTTP_NOT_FOUND },
        output => [],
    },
]
