[
    {    # Crear un nou event
        num        => 1,
        desc    => 'Crea un nou event',
        call    => 'TestCreateEvent',
        op      => 'POST',
        uri     => '/event',
        input     => {
            info        => 'EVENT 1 INFORMATION',
            description => 'DESCRIPTION',
            starts        => '2011-02-16T04:00:00',
            ends        => '2011-02-16T05:00:00',
        },
        output     => {
            status  => '201 Created',
            headers => { Location => qr{/event/\d+} },
            data     => '[]',
        },
    },
    {    # Consultar event
        num        => 2,
        desc    => 'Consulta un event',
        call    => 'TestGetEvent',
        op      => 'GET',
        uri     => \&generated_uri,
        input     => '',
        output     => {
            status  => '200 OK',
            headers => { Location => '' },
            data     =>'{"info":"EVENT 1 INFORMATION","description":"DESCRIPTION","starts":"2011-02-16T04:00:00","ends":"2011-02-16T05:00:00"}',
        },
    },
    {    # Actualitza event
        num        => 3,
        desc    => 'Actualitza un event',
        call    => 'TestUpdateEvent',
        op      => 'PUT',
        uri     => \&generated_uri,
        input     => {
            info        => 'EVENT 1 UPDATED',
            description => 'DESCRIPTION UPDATED',
            starts        => '2012-02-16T04:00:00',
            ends        => '2012-02-16T05:00:00',
        },
        output     => {
            status  => '200 OK',
            headers => { Location => '' },
            data     =>'[]',
        },
    },
    {    # Consultar event
        num        => 4,
        desc    => 'Consulta un event',
        call    => 'TestGetEvent',
        op      => 'GET',
        uri     => \&generated_uri,
        input     => '',
        output     => {
            status  => '200 OK',
            headers => { Location => '' },
            data     =>'{"info":"EVENT 1 UPDATED","description":"DESCRIPTION UPDATED","starts":"2012-02-16T04:00:00","ends":"2012-02-16T05:00:00"}',
        },
    },
    {    # Esborra event
        num        => 5,
        desc    => 'Esborra un event',
        call    => 'TestDeleteEvent',
        op      => 'DELETE',
        uri     => \&generated_uri,
        input     => '',
        output     => {
            status  => '200 OK',
            headers => { Location => '' },
            data     =>'[]',
        },
    },
    {    # Consultar event
        num        => 6,
        desc    => 'Consulta un event',
        call    => 'TestGetEvent',
        op      => 'GET',
        uri     => \&generated_uri,
        input     => '',
        output     => {
            status  => '404 Not Found',
            headers => { Location => '' },
            data     =>'[]',
        },
    },
    {    # Actualitza event
        num        => 7,
        desc    => 'Actualitza un event',
        call    => 'TestUpdateEvent',
        op      => 'PUT',
        uri     => \&generated_uri,
        input     => {
            info        => 'EVENT 1 UPDATED',
            description => 'DESCRIPTION UPDATED',
            starts        => '2012-02-16T04:00:00',
            ends        => '2012-02-16T05:00:00',
        },
        output     => {
            status  => '404 Not Found',
            headers => { Location => '' },
            data     =>'[]',
        },
    },
    {    # Crear un nou event
        num        => 8,
        desc    => 'Crea un nou event',
        call    => 'TestCreateEvent',
        op      => 'POST',
        uri     => '/event' ,
        input => {
            info        => 'EVENT 2 INFORMATION',
            description => 'DESCRIPTION',
            starts        => '2011-02-16T04:00:00',
            ends        => '2011-02-16T05:00:00',
        },
        output => {
            status  => '201 Created',
            headers => { Location => qr{/event/\d+} },
            data     => '[]',
        },
    },
]