[   {   title => 'CreaTag t1',
        uri   => { type => 'tag' },
        op    => 'POST',
        input => { id => 't1', description => 'tag 1' },
        status  => sub { shift->code == HTTP_CREATED },
        new_ids => 1,
        output  => [],
    },
    {   title => 'CreaTag t2',
        uri   => { type => 'tag' },
        op    => 'POST',
        input => { id => 't2', description => 'tag 2' },
        status  => sub { shift->code == HTTP_CREATED },
        new_ids => 1,
        output  => [],
    },
    {   title => 'CreaRecurs',
        uri   => { type => 'resource' },
        op    => 'POST',
        input => {
            description => 'aula',
            info        => 'resource info',
        },
        status  => sub { shift->code == HTTP_CREATED },
        new_ids => 1,
        output  => [],
    },
    {   title => 'GetResourceTags',
        uri   => { type => 'resource', id => \&get_generated_id },
        op    => 'GET',
        status => sub { shift->code == HTTP_MOVED_PERMANENTLY },
        output => [],
    },
    {   title => 'AssignTagToResource',
        uri => { type => 'resource', id => \&get_generated_id, tag => 't1' },
        op  => 'PUT',
        status => sub { shift->code == HTTP_OK },
        output => [],
    },
    {   title  => 'GetResourceTags',
        uri    => [ 'tag?resource=', \&get_generated_id ],
        op     => 'GET',
        status => sub { shift->code == HTTP_OK },
        output => [ { id => 't1', description => 'tag 1' } ],
    },
    {   title => 'AssignTagToResource',
        uri => { type => 'resource', id => \&get_generated_id, tag => 't2' },
        op  => 'PUT',
        status => sub { shift->code == HTTP_OK },
        output => [],
    },
    {   title  => 'GetResourceTags',
        uri    => [ 'tag?resource=', \&get_generated_id ],
        op     => 'GET',
        status => sub { shift->code == HTTP_OK },
        output => [
            { id => 't1', description => 'tag 1' },
            { id => 't2', description => 'tag 2' }
        ],
    },

]
