[   {   title  => 'CreaTag t1',
        url    => { type => 'tag' },
        method => 'POST',
        args   => { id => 't1', description => 'tag 1' },
        status  => sub { shift->code == HTTP_CREATED },
        new_ids => 1,
        result  => [],
    },
    {   title  => 'CreaTag t2',
        url    => { type => 'tag' },
        method => 'POST',
        args   => { id => 't2', description => 'tag 2' },
        status  => sub { shift->code == HTTP_CREATED },
        new_ids => 1,
        result  => [],
    },
    {   title  => 'CreaRecurs',
        url    => { type => 'resource' },
        method => 'POST',
        args   => {
            description => 'aula',
            info        => 'resource info',
        },
        status  => sub { shift->code == HTTP_CREATED },
        new_ids => 1,
        result  => [],
    },
    {   title  => 'GetResourceTags',
        url    => { type => 'resource', id => \&get_generated_id },
        method => 'GET',
        status => sub { shift->code == HTTP_MOVED_PERMANENTLY },
        result => [],
    },
    {   title => 'AssignTagToResource',
        url => { type => 'resource', id => \&get_generated_id, tag => 't1' },
        method => 'PUT',

        #args   => { },
        status => sub { shift->code == HTTP_OK },
        result => [],
    },
    {   title  => 'GetResourceTags',
        url    => [ 'tag?resource=', \&get_generated_id ],
        method => 'GET',
        status => sub { shift->code == HTTP_OK },
        result => [ { id => 't1', description => 'tag 1' } ],
    },
    {   title => 'AssignTagToResource',
        url => { type => 'resource', id => \&get_generated_id, tag => 't2' },
        method => 'PUT',

        #args   => { },
        status => sub { shift->code == HTTP_OK },
        result => [],
    },
    {   title  => 'GetResourceTags',
        url    => [ 'tag?resource=', \&get_generated_id ],
        method => 'GET',
        status => sub { shift->code == HTTP_OK },
        result => [
            { id => 't1', description => 'tag 1' },
            { id => 't2', description => 'tag 2' }
        ],
    },

]
