[
    {    # Llistar resources buida
        num        => 1,
        desc    => 'Consulta un resource',
        call    => 'TestGetEmptyListResource',
        op      => 'GET',
        uri     => \&uri_resource,
        input     => '',
        output     => {
            status  => '200 OK',
            headers => { Location => '' },
            data     =>'[]',
        },
    },
    {    # Crear un nou resource amb description incorrecta
        num        => 2,
        desc    => 'Crea un nou resource amb desciprio incorrecta',
        call    => 'TestCreateResourceWithBadDescription',
        op      => 'POST',
        uri     => '/resource',
        input     => {
            info        => '',
            description => '12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890',
        },
        output     => {
            status  => '400 Bad Request',
            headers => { Location => '' },
            data     =>'[]',
        },
    },
    {    # Crear un nou resource
        num        => 3,
        desc    => 'Crea un nou resource',
        call    => 'TestCreateResource',
        op      => 'POST',
        uri     => '/resource' ,
        input => {
            info        => 'RESOURCE 1 INFORMATION',
            description => 'DESCRIPTION',
        },
        output => {
            status  => '201 Created',
            headers => { Location => qr{/resource/\d+} },
            data     => '[]',
        },
    },
    {    # Consultar resource
        num        => 4,
        desc    => 'Consulta un resource',
        call    => 'TestGetResource',
        op      => 'GET',
        uri     => \&generated_uri_resource,
        input     => '',
        output     => {
            status  => '200 OK',
            headers => { Location => '' },
            data     =>'{"info":"RESOURCE 1 INFORMATION","description":"DESCRIPTION"}',
        },
    },
    {    # Actualitza resource
        num        => 5,
        desc    => 'Actualitza un resource',
        call    => 'TestUpdateResource',
        op      => 'PUT',
        uri     => \&generated_uri_resource,
        input     => {
            info        => 'RESOURCE 1 UPDATED',
            description => 'DESCRIPTION UPDATED',
        },
        output     => {
            status  => '200 OK',
            headers => { Location => '' },
            data     =>'[]',
        },
    },
    {    # Consultar resource
        num        => 6,
        desc    => 'Consulta un resource',
        call    => 'TestGetResource',
        op      => 'GET',
        uri     => \&generated_uri_resource,
        input     => '',
        output     => {
            status  => '200 OK',
            headers => { Location => '' },
            data     =>'{"info":"RESOURCE 1 UPDATED","description":"DESCRIPTION UPDATED"}',
        },
    },
    {    # Esborra resource
        num        => 7,
        desc    => 'Esborra un resource',
        call    => 'TestDeleteResource',
        op      => 'DELETE',
        uri     => \&generated_uri_resource,
        input     => '',
        output     => {
            status  => '200 OK',
            headers => { Location => '' },
            data     =>'[]',
        },
    },
    {    # Consultar resource ja esborrat
        num        => 8,
        desc    => 'Consulta un resource ja esborrat',
        call    => 'TestGetResourceDeleted',
        op      => 'GET',
        uri     => \&generated_uri_resource,
        input     => '',
        output     => {
            status  => '404 Not Found',
            headers => { Location => '' },
            data     =>'[]',
        },
    },
    {    # Actualitza resource ja esborrat
        num        => 9,
        desc    => 'Actualitza un resource',
        call    => 'TestUpdateResourceDeleted',
        op      => 'PUT',
        uri     => \&generated_uri_resource,
        input     => {
            info        => 'RESOURCE 1 UPDATED',
            description => 'DESCRIPTION UPDATED',
        },
        output     => {
            status  => '404 Not Found',
            headers => { Location => '' },
            data     =>'[]',
        },
    },
    {    # Crear un nou resource
        num        => 10,
        desc    => 'Crea un nou resource',
        call    => 'TestCreateResource',
        op      => 'POST',
        uri     => '/resource' ,
        input => {
            info        => 'RESOURCE 2 INFORMATION',
            description => 'DESCRIPTION',
        },
        output => {
            status  => '201 Created',
            headers => { Location => qr{/resource/\d+} },
            data     => '[]',
        },
    },
    {    # Crear un nou resource
        num        => 11,
        desc    => 'Crea un nou resource',
        call    => 'TestCreateResource',
        op      => 'POST',
        uri     => '/resource' ,
        input => {
            info        => 'RESOURCE 3 INFORMATION',
            description => 'DESCRIPTION_',
        },
        output => {
            status  => '201 Created',
            headers => { Location => qr{/resource/\d+} },
            data     => '[]',
        },
    },   
    {    # Actualitzar resource
        num        => 12,
        desc    => 'Actualitza un resource',
        call    => 'TestUpdateResource',
        op      => 'PUT',
        uri     => \&generated_uri_resource,
        input     => {
            info        => 'RESOURCE 3 UPDATED',
            description => 'DESCRIPTION_ UPDATED',
        },
        output     => {
            status  => '200 OK',
            headers => { Location => '' },
            data     =>'[]',
        },
    },
    {    # Actualitzar resource amb descripcio ja usada
        num        => 13,
        desc    => 'Actualitza un resource amb descripcio ja usada',
        call    => 'TestUpdateResourceDescriptionAlreadyExists',
        op      => 'PUT',
        uri     => \&generated_uri_resource,
        input     => {
            info        => 'RESOURCE 3 UPDATED',
            description => 'DESCRIPTION_ UPDATED',
        },
        output     => {
            status  => '409 Conflict',
            headers => { Location => '' },
            data     =>'[]',
        },
    },   
    {    # Actualitzar resource amb descripcio incorrecta
        num        => 14,
        desc    => 'Actualitza un resource amb descripcio incorrecta',
        call    => 'TestUpdateResourceBadDescription',
        op      => 'PUT',
        uri     => \&generated_uri_resource,
        input     => {
            info        => 'RESOURCE 3 UPDATED',
            description => 'mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm',
        },
        output     => {
            status  => '400 Bad Request',
            headers => { Location => '' },
            data     =>'[]',
        },
    }, 
    {    # Esborra resource
        num        => 15,
        desc    => 'Esborra un resource',
        call    => 'TestDeleteResource',
        op      => 'DELETE',
        uri     => \&generated_uri_resource,
        input     => '',
        output     => {
            status  => '200 OK',
            headers => { Location => '' },
            data     =>'[]',
        },
    },
    {    # Esborra resource ja esborrat
        num        => 16,
        desc    => 'Esborra un resource ja esborrat',
        call    => 'TestDeleteResourceAlreadyDeleted',
        op      => 'DELETE',
        uri     => \&generated_uri_resource,
        input     => '',
        output     => {
            status  => '404 Not Found',
            headers => { Location => '' },
            data     =>'[]',
        },
    },
    {    # Consultar resource
        num        => 17,
        desc    => 'Consulta un resource ja esborrat',
        call    => 'TestGetResourceYetDeleted',
        op      => 'GET',
        uri     => \&generated_uri_resource,
        input     => '',
        output     => {
            status  => '404 Not Found',
            headers => { Location => '' },
            data     =>'[]',
        },
    },  
    {    # Crear un nou resource
        num        => 18,
        desc    => 'Crea un nou resource',
        call    => 'TestCreateResource',
        op      => 'POST',
        uri     => '/resource' ,
        input => {
            info        => 'RESOURCE 4 INFORMATION',
            description => 'DESCRIPTION_',
        },
        output => {
            status  => '201 Created',
            headers => { Location => qr{/resource/\d+} },
            data     => '[]',
        },
    },
    {    # Crear un nou resource
        num     => 19,
        desc    => 'Crea un nou resource',
        call    => 'TestCreateResourceDescriptionAlreadyExists',
        op      => 'POST',
        uri     => '/resource' ,
        input 	=> {
            info        => 'RESOURCE 5 INFORMATION',
            description => 'DESCRIPTION_',
        },
        output => {
            status  => '409 Conflict',
            headers => { Location => '' },
            data     => '[]',
        },
    },
] 
