[
    {    # Consultar llistat events
        num        => 1,
        desc    => 'Consulta llistat buit',
        call    => 'TestGetEmptyEventList',
        op      => 'GET',
        uri     => \&event_uri,
        input     => '',
        output     => {
            status  => '200 OK',
            headers => { Location => '' },
            data     =>'[]',
        },
    },
    
    {    # Crear un nou event incorrecte
        num        => 2,
        desc    => 'Crea un nou event',
        call    => 'TestCreateInvalidEvent',
        op      => 'POST',
        uri     => '/event',
        input     => {
            info        => 'EVENT 1 INFORMATION',
            description => 'DESCRIPTION',
            starts        => '',
            ends        => '2011-02-16T05:00:00',
        },
        output     => {
            status  => '400 Bad Request',
            data     => '[]',
        },
    },
    {    # Crear un nou event
        num        => 3,
        desc    => 'Crea un nou event',
        call    => 'TestCreateEvent',
        op      => 'POST',
        uri     => '/event' ,
        input => {
            info        => 'EVENT 1 INFORMATION',
            description => 'DESCRIPTION',
            starts        => '2011-02-16T04:00:00',
            ends        => '2011-02-16T05:00:00',
        },
        output => {
            status  => '201 Created',
            headers => { Location => qr{/event/\d+} },
            data     => '[]',
        },
    },
    {    # Consultar un event 
        num        => 4,
        desc    => 'Consulta un event',
        call    => 'TestGetEvent',
        op      => 'GET',
        uri     => \&generated_uri,
        input     => '',
        output     => {
            status  => '200 OK',
            headers => { Location => '' },
            data     =>'{"info":"EVENT 1 INFORMATION","description":"DESCRIPTION","starts":"2011-02-16T04:00:00","ends":"2011-02-16T05:00:00"}',
        },
    },
    {    # Consultar llistat de events
        num        => 5,
        desc    => 'Consulta un llistat de events',
        call    => 'TestGetNotEmptyEventList',
        op      => 'GET',
        uri     => \&event_uri,
        input     => '',
        output     => {
            status  => '200 OK',
            headers => { Location => '' },
            data     =>'[{"info":"EVENT 1 INFORMATION","description":"DESCRIPTION","starts":"2011-02-16T04:00:00","ends":"2011-02-16T05:00:00"}]',
        },
    },
    {    # Actualitza event
        num        => 6,
        desc    => 'Actualitza un event',
        call    => 'TestUpdateEvent',
        op      => 'PUT',
        uri     => \&generated_uri,
        input     => {
            info        => 'EVENT 1 UPDATED',
            description => 'DESCRIPTION UPDATED',
            starts        => '2012-02-16T04:00:00',
            ends        => '2012-02-16T05:00:00',
        },
        output     => {
            status  => '200 OK',
            headers => { Location => '' },
            data     =>'[]',
        },
    },
    {    # Consultar event
        num        => 7,
        desc    => 'Consulta un event',
        call    => 'TestGetEvent',
        op      => 'GET',
        uri     => \&generated_uri,
        input     => '',
        output     => {
            status  => '200 OK',
            headers => { Location => '' },
            data     =>'{"info":"EVENT 1 UPDATED","description":"DESCRIPTION UPDATED","starts":"2012-02-16T04:00:00","ends":"2012-02-16T05:00:00"}',
        },
    },
    {    # Esborra event
        num        => 8,
        desc    => 'Esborra un event',
        call    => 'TestDeleteEvent',
        op      => 'DELETE',
        uri     => \&generated_uri,
        input     => '',
        output     => {
            status  => '200 OK',
            headers => { Location => '' },
            data     =>'[]',
        },
    },
    {    # Consultar llistat buit
        num        => 9,
        desc    => 'Consulta un llistat buit',
        call    => 'TestGetEmptyEventList',
        op      => 'GET',
        uri     => \&event_uri,
        input     => '',
        output     => {
            status  => '200 OK',
            headers => { Location => '' },
            data     =>'[]',
        },
    },
    {    # Consultar event
        num        => 10,
        desc    => 'Consulta un event esborrat',
        call    => 'TestGetEventNotFound',
        op      => 'GET',
        uri     => \&generated_uri,
        input     => '',
        output     => {
            status  => '404 Not Found',
            headers => { Location => '' },
            data     =>'[]',
        },
    },
    {    # Actualitza event
        num        => 11,
        desc    => 'Actualitza un event esborrat',
        call    => 'TestUpdateEventNotFound',
        op      => 'PUT',
        uri     => \&generated_uri,
        input     => {
            info        => 'EVENT 1 UPDATED',
            description => 'DESCRIPTION UPDATED',
            starts        => '2012-02-16T04:00:00',
            ends        => '2012-02-16T05:00:00',
        },
        output     => {
            status  => '404 Not Found',
            headers => { Location => '' },
            data     =>'[]',
        },
    },
    {    # Crear un nou event
        num        => 12,
        desc    => 'Crea un nou event',
        call    => 'TestCreateEvent',
        op      => 'POST',
        uri     => '/event' ,
        input => {
            info        => 'EVENT 2 INFORMATION',
            description => 'DESCRIPTION',
            starts        => '2011-02-16T04:00:00',
            ends        => '2011-02-16T05:00:00',
        },
        output => {
            status  => '201 Created',
            headers => { Location => qr{/event/\d+} },
            data     => '[]',
        },
    },
    {    # Crear un nou event
        num        => 13,
        desc    => 'Crea un nou event',
        call    => 'TestCreateEvent',
        op      => 'POST',
        uri     => '/event' ,
        input => {
            info        => 'EVENT 3 INFORMATION',
            description => 'DESCRIPTION_',
            starts        => '2011-02-16T04:00:00',
            ends        => '2011-02-16T05:00:00',
        },
        output => {
            status  => '201 Created',
            headers => { Location => qr{/event/\d+} },
            data     => '[]',
        },
    },
    {    # Consultar llistat de events
        num        => 14,
        desc    => 'Consulta un llistat de events',
        call    => 'TestGetNotEmptyListEvent',
        op      => 'GET',
        uri     => \&event_uri,
        input     => '',
        output     => {
            status  => '200 OK',
            headers => { Location => '' },
            data     =>'[{"info":"EVENT 2 INFORMATION","description":"DESCRIPTION","starts":"2011-02-16T04:00:00","ends":"2011-02-16T05:00:00"}, {"info":"EVENT 3 INFORMATION","description":"DESCRIPTION_","starts":"2011-02-16T04:00:00","ends":"2011-02-16T05:00:00"}]',
        },
    },
    {    # Actualitza event
        num        => 15,
        desc    => 'Actualitza un event',
        call    => 'TestUpdateEvent',
        op      => 'PUT',
        uri     => \&generated_uri,
        input     => {
            info        => 'EVENT 3 UPDATED',
            description => 'DESCRIPTION_ UPDATED',
            starts        => '2012-02-16T04:00:00',
            ends        => '2012-02-16T05:00:00',
        },
        output     => {
            status  => '200 OK',
            headers => { Location => '' },
            data     =>'[]',
        },
    },
    {    # Actualitza event
        num        => 16,
        desc    => 'Actualitza incorrectament un event',
        call    => 'TestUpdateEventInvalid',
        op      => 'PUT',
        uri     => \&generated_uri,
        input     => {
            info        => 'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
            description => 'DESCRIPTION_ UPDATED',
            starts        => '2012-02-16T04:00:00',
            ends        => '2012-02-16T05:00:00',
        },
        output     => {
            status  => '400 Bad Request',
            headers => { Location => '' },
            data     =>'[]',
        },
    },   
    {    # Actualitza event
        num        => 17,
        desc    => 'Actualitza incorrectament un event',
        call    => 'TestUpdateEventInvalid',
        op      => 'PUT',
        uri     => \&generated_uri,
        input     => {
            info        => 'EVENT 3 UPDATED',
            description => 'mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm',
            starts        => '2012-02-16T04:00:00',
            ends        => '2012-02-16T05:00:00',
        },
        output     => {
            status  => '400 Bad Request',
            headers => { Location => '' },
            data     =>'[]',
        },
    }, 
    {    # Esborra event
        num        => 18,
        desc    => 'Esborra un event',
        call    => 'TestDeleteEvent',
        op      => 'DELETE',
        uri     => \&generated_uri,
        input     => '',
        output     => {
            status  => '200 OK',
            headers => { Location => '' },
            data     =>'[]',
        },
    },
    {    # Consultar llistat de events
        num        => 19,
        desc    => 'Consulta un llistat de events',
        call    => 'TestGetNotEmptyListEvent',
        op      => 'GET',
        uri     => \&event_uri,
        input     => '',
        output     => {
            status  => '200 OK',
            headers => { Location => '' },
            data     =>'[{"info":"EVENT 2 INFORMATION","description":"DESCRIPTION","starts":"2011-02-16T04:00:00","ends":"2011-02-16T05:00:00"}]',
        },
    },
    {    # Esborra event
        num        => 20,
        desc    => 'Esborra un event ja esborrat',
        call    => 'TestDeleteEventNotFound',
        op      => 'DELETE',
        uri     => \&generated_uri,
        input     => '',
        output     => {
            status  => '404 Not Found',
            headers => { Location => '' },
            data     =>'[]',
        },
    },
    {    # Consultar event
        num        => 21,
        desc    => 'Consulta un event ja esborrat',
        call    => 'TestGetEventNotFound',
        op      => 'GET',
        uri     => \&generated_uri,
        input     => '',
        output     => {
            status  => '404 Not Found',
            headers => { Location => '' },
            data     =>'[]',
        },
    },  
    {    # Crear un nou event
        num        => 22,
        desc    => 'Crea un nou event',
        call    => 'TestCreateEvent',
        op      => 'POST',
        uri     => '/event' ,
        input => {
            info        => 'EVENT 4 INFORMATION',
            description => 'DESCRIPTION_',
            starts        => '2011-02-16T04:00:00',
            ends        => '2011-02-16T05:00:00',
        },
        output => {
            status  => '201 Created',
            headers => { Location => qr{/event/\d+} },
            data     => '[]',
        },
    },
    {    # Crear un nou event
        num        => 23,
        desc    => 'Crea un nou event',
        call    => 'TestCreateEvent',
        op      => 'POST',
        uri     => '/event' ,
        input => {
            info        => 'EVENT 5 INFORMATION',
            description => 'DESCRIPTION_',
            starts        => '2011-02-16T04:00:00',
            ends        => '2011-02-16T05:00:00',
        },
        output => {
            status  => '201 Created',
            headers => { Location => qr{/event/\d+} },
            data     => '[]',
        },
    },
    {    # Consultar llistat events
        num        => 24,
        desc    => 'Consulta un llistat de events',
        call    => 'TestGeNotEmptyEventList',
        op      => 'GET',
        uri     => \&event_uri,
        input     => '',
        output     => {
            status  => '200 OK',
            headers => { Location => '' },
            data     =>'[{"info":"EVENT 2 INFORMATION","description":"DESCRIPTION","starts":"2011-02-16T04:00:00","ends":"2011-02-16T05:00:00"}, {"info":"EVENT 4 INFORMATION","description":"DESCRIPTION_","starts":"2011-02-16T04:00:00","ends":"2011-02-16T05:00:00"}, {"info":"EVENT 5 INFORMATION","description":"DESCRIPTION_","starts":"2011-02-16T04:00:00","ends":"2011-02-16T05:00:00"}]',
        },
    },
] 

